/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproject;
import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Thomas
 */
public class NTUSpotify extends javax.swing.JFrame {

    /**
     * Creates new form NTUSpotify
     */
    
    DefaultListModel<String> GenreListModel;
    DefaultListModel<String> RequestsListModel;
    DefaultListModel<String> OnlineListModel;
    DefaultListModel<String> FriendListModel;
    DefaultListModel<String> SharedSongsListModel;
    SocketClient socketClient = new SocketClient();
    ExecutorService music = Executors.newFixedThreadPool(4);
    
    public NTUSpotify() {
        
        GenreListModel = new DefaultListModel<String>();
        RequestsListModel = new DefaultListModel<String>();
        OnlineListModel = new DefaultListModel<String>();
        FriendListModel = new DefaultListModel<String>();
        SharedSongsListModel = new DefaultListModel<String>();
        
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
        this.setTitle("NTU Music Network");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        mainPanel = new javax.swing.JPanel();
        logIn = new javax.swing.JPanel();
        UsernameLabel1 = new javax.swing.JLabel();
        PasswordLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        RegisterButton1 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        ConnectionLabel = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        RegisterButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        GenresLabel = new javax.swing.JLabel();
        GenreComboBox = new javax.swing.JComboBox<>();
        AddButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GenreList = new javax.swing.JList<>();
        UsernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        DOBTextField = new javax.swing.JTextField();
        RegisterPasswordField = new javax.swing.JPasswordField();
        StatusLabel = new javax.swing.JLabel();
        home = new javax.swing.JTabbedPane();
        homejPanel = new javax.swing.JPanel();
        friendLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sharedSongs = new javax.swing.JList<>();
        playButton = new javax.swing.JButton();
        informationLabel = new javax.swing.JLabel();
        sharedSongsLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        uploadSongsButton = new javax.swing.JButton();
        currentSongLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInformationPane = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        friendInformationPane = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        friendList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        postsjPanel = new javax.swing.JPanel();
        sendButton = new javax.swing.JButton();
        postTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        postTextArea = new javax.swing.JTextArea();
        postLabel = new javax.swing.JLabel();
        friendsChatjPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        connectedPeopleList = new javax.swing.JList<>();
        connectedPeoplejLabel = new javax.swing.JLabel();
        requestsjLabel = new javax.swing.JLabel();
        requestFriendshipjButton = new javax.swing.JButton();
        chatjButton = new javax.swing.JButton();
        acceptjButton = new javax.swing.JButton();
        refusejButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        requestsList = new javax.swing.JList<>();
        friendRequestStatusLabel = new javax.swing.JLabel();
        chat = new javax.swing.JPanel();
        chatjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        messagejTextField = new javax.swing.JTextField();
        messagejLabel = new javax.swing.JLabel();
        sendjButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        messagesjTextArea = new javax.swing.JTextArea();
        backjButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        UsernameLabel1.setText("Username:");

        PasswordLabel1.setText("Password:");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        RegisterButton1.setText("Register");
        RegisterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButton1ActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInLayout = new javax.swing.GroupLayout(logIn);
        logIn.setLayout(logInLayout);
        logInLayout.setHorizontalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInLayout.createSequentialGroup()
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInLayout.createSequentialGroup()
                                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegisterButton1))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInLayout.createSequentialGroup()
                                .addComponent(PasswordLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(logInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConnectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(UsernameLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        logInLayout.setVerticalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConnectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel1)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(LoginButton)
                .addGap(1, 1, 1)
                .addComponent(RegisterButton1)
                .addGap(1, 1, 1)
                .addComponent(ExitButton)
                .addContainerGap())
        );

        mainPanel.add(logIn, "card3");

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        GenresLabel.setText("Pick your favourite genres");

        GenreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambient Music", "Blues", "Classical Music", "Country Music", "Disco", "Drum and Bass", "Dubstep", "Heavy Metal", "Hip Hop Music", "House", "Jazz", "Pop Music", "Reggae", "Rock", "Techno" }));

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        GenreList.setModel(GenreListModel);
        jScrollPane2.setViewportView(GenreList);

        UsernameLabel.setText("Username:");

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        PasswordLabel.setText("Password:");

        DOBLabel.setText("Date of Birth (DD/MM/YYYY):");

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        DOBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DOBLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(DOBTextField)
                            .addComponent(RegisterPasswordField)))
                    .addGroup(registerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RegisterButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton))
                    .addGroup(registerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StatusLabel)))
                .addGap(18, 18, 18)
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GenresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap())
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerLayout.createSequentialGroup()
                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerLayout.createSequentialGroup()
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UsernameLabel)
                                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PasswordLabel)
                                    .addComponent(RegisterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DOBLabel)
                                    .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(StatusLabel))
                        .addGap(56, 56, 56)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegisterButton)
                            .addComponent(CancelButton)))
                    .addGroup(registerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenresLabel)
                            .addComponent(AddButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        mainPanel.add(register, "card2");

        friendLabel.setText("Friends");

        sharedSongs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Be Happy" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sharedSongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sharedSongsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(sharedSongs);

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        informationLabel.setText("Information");

        sharedSongsLabel.setText("Shared Songs");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        uploadSongsButton.setText("Upload Songs");
        uploadSongsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadSongsButtonActionPerformed(evt);
            }
        });

        currentSongLabel.setText("Current Song");

        userInformationPane.setEditable(false);
        jScrollPane1.setViewportView(userInformationPane);

        friendInformationPane.setEditable(false);
        jScrollPane11.setViewportView(friendInformationPane);

        friendList.setModel(FriendListModel);
        friendList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                friendListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(friendList);

        jButton1.setText("Upload Picture");

        javax.swing.GroupLayout homejPanelLayout = new javax.swing.GroupLayout(homejPanel);
        homejPanel.setLayout(homejPanelLayout);
        homejPanelLayout.setHorizontalGroup(
            homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(friendLabel)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homejPanelLayout.createSequentialGroup()
                                .addComponent(informationLabel)
                                .addGap(0, 137, Short.MAX_VALUE))
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(uploadSongsButton))
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(playButton)
                        .addGap(10, 10, 10)
                        .addComponent(stopButton))
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(currentSongLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sharedSongsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homejPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, logoutButton});

        homejPanelLayout.setVerticalGroup(
            homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(friendLabel)
                    .addComponent(informationLabel)
                    .addComponent(sharedSongsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homejPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton))
                    .addGroup(homejPanelLayout.createSequentialGroup()
                        .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homejPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homejPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(currentSongLabel)
                                .addGap(14, 14, 14)
                                .addGroup(homejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(playButton)
                                    .addComponent(stopButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uploadSongsButton)))))
                .addContainerGap())
        );

        home.addTab("Home", homejPanel);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        postTextArea.setEditable(false);
        postTextArea.setColumns(20);
        postTextArea.setRows(5);
        jScrollPane4.setViewportView(postTextArea);

        postLabel.setText("Post:");

        javax.swing.GroupLayout postsjPanelLayout = new javax.swing.GroupLayout(postsjPanel);
        postsjPanel.setLayout(postsjPanelLayout);
        postsjPanelLayout.setHorizontalGroup(
            postsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(postsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(postsjPanelLayout.createSequentialGroup()
                        .addComponent(postLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(postTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        postsjPanelLayout.setVerticalGroup(
            postsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postsjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(postsjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton)
                    .addComponent(postLabel)))
        );

        home.addTab("Posts", postsjPanel);

        connectedPeopleList.setModel(OnlineListModel);
        jScrollPane6.setViewportView(connectedPeopleList);

        connectedPeoplejLabel.setText("List of connected people");

        requestsjLabel.setText("Friendship Requests");

        requestFriendshipjButton.setText("Request Friendship");
        requestFriendshipjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestFriendshipjButtonActionPerformed(evt);
            }
        });

        chatjButton.setText("Chat");
        chatjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatjButtonActionPerformed(evt);
            }
        });

        acceptjButton.setText("Accept");
        acceptjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptjButtonActionPerformed(evt);
            }
        });

        refusejButton.setText("Refuse");
        refusejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refusejButtonActionPerformed(evt);
            }
        });

        requestsList.setModel(RequestsListModel);
        requestsList.setToolTipText("");
        jScrollPane7.setViewportView(requestsList);

        javax.swing.GroupLayout friendsChatjPanelLayout = new javax.swing.GroupLayout(friendsChatjPanel);
        friendsChatjPanel.setLayout(friendsChatjPanelLayout);
        friendsChatjPanelLayout.setHorizontalGroup(
            friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendsChatjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendsChatjPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(requestFriendshipjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chatjButton)
                            .addComponent(friendRequestStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(connectedPeoplejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestsjLabel)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceptjButton)
                    .addComponent(refusejButton))
                .addGap(11, 11, 11))
        );
        friendsChatjPanelLayout.setVerticalGroup(
            friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendsChatjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectedPeoplejLabel)
                    .addComponent(requestsjLabel))
                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, friendsChatjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(friendRequestStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestFriendshipjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatjButton)
                        .addGap(94, 94, 94))
                    .addGroup(friendsChatjPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(friendsChatjPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(acceptjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refusejButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, friendsChatjPanelLayout.createSequentialGroup()
                                .addGroup(friendsChatjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane6))
                                .addContainerGap())))))
        );

        home.addTab("Friends & Chat", friendsChatjPanel);

        mainPanel.add(home, "card4");

        chatjLabel.setText("Chat: ");

        namejLabel.setText("Name");

        messagejLabel.setText("Message:");

        sendjButton.setText("Send");

        messagesjTextArea.setColumns(20);
        messagesjTextArea.setRows(5);
        jScrollPane8.setViewportView(messagesjTextArea);

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chatLayout = new javax.swing.GroupLayout(chat);
        chat.setLayout(chatLayout);
        chatLayout.setHorizontalGroup(
            chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(chatLayout.createSequentialGroup()
                        .addComponent(chatjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(511, 511, 511))
                    .addGroup(chatLayout.createSequentialGroup()
                        .addComponent(messagejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagejTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backjButton)))
                .addContainerGap())
        );
        chatLayout.setVerticalGroup(
            chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chatjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendjButton)
                    .addComponent(backjButton)
                    .addComponent(messagejLabel))
                .addContainerGap())
        );

        mainPanel.add(chat, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(logIn);
        mainPanel.repaint();
        mainPanel.revalidate(); 
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        String genre = GenreComboBox.getSelectedItem().toString();
        GenreListModel.addElement(genre);
    }//GEN-LAST:event_AddButtonActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        String genre = GenreList.getSelectedValue();
        GenreListModel.removeElement(genre);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void DOBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
       
        String username = usernameField.getText();
        String password = PasswordField.getText();
        String message = username + "-" + password + "-" + "L";
        String isCorrect = socketClient.request("checkCredentials",message);
        if (isCorrect.equals("correct"))
        {
        socketClient.request("loginUser", username);
        this.setTitle("NTU Music Network - "+ username);
        
        //Get user information and display it
        String content = socketClient.request("getUserInformation",username);
        String[] information = content.split("-");
        String userInformation = "Your information:\r\n";
        
        for (int i = 0; i<information.length;i++)
        {
            userInformation+= information[i]+"\r\n";
        }
        
        userInformationPane.setText(userInformation);
        //Timer to run update functions once user has logged in i.e. updating online list, friend requests
        java.util.Timer t = new java.util.Timer();
        t.schedule(new TimerTask() 
        {
             @Override
             public void run() 
             {
                OnlineListModel.removeAllElements();
                String usernames = socketClient.request("updateLoginList","nodata-nodata");
                String[] usernameList = usernames.split("-");
                
                for (int i = 1; i < usernameList.length; i++)
                {
                    OnlineListModel.addElement(usernameList[i]);
                }
                
                String posts = socketClient.request("updatePostList","nodata-nodata");
                postTextArea.setText(posts);
                
                FriendListModel.removeAllElements();
                String friends = socketClient.request("updateFriendList", username);
                String[] friendNames = friends.split("-");
                
                for (int i = 0; i<friendNames.length; i++){
                    FriendListModel.addElement(friendNames[i]);
                }

                String friendRequest = socketClient.request("getFriendRequest",username);
                String[] friendRequests = friendRequest.split("-");
                RequestsListModel.removeAllElements();
                for (int i = 0; i<friendRequests.length; i++){
                RequestsListModel.addElement(friendRequests[i]);
                }

            }
        }, 0, 10000);
        
        
        ConnectionLabel.setText("");
        mainPanel.removeAll();
        mainPanel.add(home);
        mainPanel.repaint();
        mainPanel.revalidate();
        }
        else if (isCorrect.equals("server")) {
            ConnectionLabel.setText("Server not running");
        }
        else {
            ConnectionLabel.setText("Username or password incorrect");
        }
        
         
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegisterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButton1ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(register);
        mainPanel.repaint();
        mainPanel.revalidate();
        ConnectionLabel.setText("");
        usernameField.setText("");
        PasswordField.setText("");
    }//GEN-LAST:event_RegisterButton1ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        String songName = sharedSongs.getSelectedValue();
        currentSongLabel.setText(songName);
        
        //Creating a new thread which plays the song in the background
        music.submit(new Runnable() {
        public void run() {
            socketClient.request("playSong",songName + "-"+ "play");
        }
        });  
    }//GEN-LAST:event_playButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        String username = usernameField.getText();
        socketClient.request("logoutUser",username);
        this.setTitle("NTU Music Network");
        mainPanel.removeAll();
        mainPanel.add(logIn);
        mainPanel.repaint();
        mainPanel.revalidate();
        usernameField.setText("");
        PasswordField.setText("");
        
        String songName = currentSongLabel.getText();
        socketClient.request("playSong",songName + "-" + "stop");  
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(home);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_backjButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
       String username = usernameTextField.getText();
       String password = RegisterPasswordField.getText();
       String dateOfBirth = DOBTextField.getText();
       String message = username + "-" + password + "-"+ "R";
       //Checking if a user with the same username already exists
       String exists = socketClient.request("checkCredentials",message);
       
       if (exists.equals("incorrect"))
       {
            String genresString = "";
       
           for (int i=0;i < GenreList.getModel().getSize();i++)
           {
                genresString += GenreList.getModel().getElementAt(i);
                genresString += "_";
           }
           message = username+"-"+password+"-"+dateOfBirth+"-"+genresString;
           socketClient.request("registering", message);
           
            ConnectionLabel.setText("");
            mainPanel.removeAll();
            mainPanel.add(logIn);
            mainPanel.repaint();
            mainPanel.revalidate(); 
        }
        else if (exists.equals("server")) {
            StatusLabel.setText("Server not running");
        }
        else {
            StatusLabel.setText("Username already exists");
        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NTUSpotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NTUSpotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NTUSpotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NTUSpotify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NTUSpotify().setVisible(true);
            }
        });
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String post = postTextField.getText();
        String username = usernameField.getText();
        String message = username + "-" + post;
        socketClient.request("makePost", message);
        postTextField.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void sharedSongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sharedSongsValueChanged

    }//GEN-LAST:event_sharedSongsValueChanged

    private void requestFriendshipjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestFriendshipjButtonActionPerformed
        String friend = connectedPeopleList.getSelectedValue();
        String username = usernameField.getText();
        friend =  friend.replace("\r\n", "");
        String message = username + "-" + friend;
        if (!friend.equals(username)){
        friendRequestStatusLabel.setText(socketClient.request("friendRequest", message));
        }
        else
        {
            friendRequestStatusLabel.setText("Cannot add self");
        }
    }//GEN-LAST:event_requestFriendshipjButtonActionPerformed

    private void chatjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatjButtonActionPerformed
        mainPanel.removeAll();
        mainPanel.add(chat);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_chatjButtonActionPerformed

    private void acceptjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptjButtonActionPerformed
        String request = requestsList.getSelectedValue();
        RequestsListModel.removeElement(request);
        String acceptRequest = socketClient.request("acceptRequest", usernameField.getText()+"-"+request+"-"+"accept");
    }//GEN-LAST:event_acceptjButtonActionPerformed

    private void refusejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refusejButtonActionPerformed
        String request = requestsList.getSelectedValue();
        socketClient.request("removeRequest", usernameField.getText()+"-"+request);
        RequestsListModel.removeElement(request);
    }//GEN-LAST:event_refusejButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        String songName = currentSongLabel.getText();
        socketClient.request("playSong",songName + "-" + "stop");  
    }//GEN-LAST:event_stopButtonActionPerformed

    private void uploadSongsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadSongsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadSongsButtonActionPerformed

    private void friendListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_friendListValueChanged
        String name = friendList.getSelectedValue();
        String content = socketClient.request("getUserInformation",name);
        
        String[] information = content.split("-");
        String friendInformation = "Friend information:\n";
        
        for (int i = 0; i<information.length;i++)
        {
            friendInformation+= information[i]+"\n";
        }
        
        friendInformationPane.setText(friendInformation);
    }//GEN-LAST:event_friendListValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel ConnectionLabel;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox<String> GenreComboBox;
    private javax.swing.JList<String> GenreList;
    private javax.swing.JLabel GenresLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel1;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JButton RegisterButton1;
    private javax.swing.JPasswordField RegisterPasswordField;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel1;
    private javax.swing.JButton acceptjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JPanel chat;
    private javax.swing.JButton chatjButton;
    private javax.swing.JLabel chatjLabel;
    private javax.swing.JList<String> connectedPeopleList;
    private javax.swing.JLabel connectedPeoplejLabel;
    private javax.swing.JLabel currentSongLabel;
    private javax.swing.JTextPane friendInformationPane;
    private javax.swing.JLabel friendLabel;
    private javax.swing.JList<String> friendList;
    private javax.swing.JLabel friendRequestStatusLabel;
    private javax.swing.JPanel friendsChatjPanel;
    private javax.swing.JTabbedPane home;
    private javax.swing.JPanel homejPanel;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel logIn;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JTextField messagejTextField;
    private javax.swing.JTextArea messagesjTextArea;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel postLabel;
    private javax.swing.JTextArea postTextArea;
    private javax.swing.JTextField postTextField;
    private javax.swing.JPanel postsjPanel;
    private javax.swing.JButton refusejButton;
    private javax.swing.JPanel register;
    private javax.swing.JButton requestFriendshipjButton;
    private javax.swing.JList<String> requestsList;
    private javax.swing.JLabel requestsjLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton sendjButton;
    private javax.swing.JList<String> sharedSongs;
    private javax.swing.JLabel sharedSongsLabel;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton uploadSongsButton;
    private javax.swing.JTextPane userInformationPane;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
 
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("NTU.png")));
    }

}


 
